# Generated by Django 4.1.1 on 2022-10-14 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
